language: python
python:
  - "3.11"
install:
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - wget https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
  - conda activate test-environment
  - conda install boost
  - pip install -U -r requirements.txt
  - pip install -U -r requirements-dev.txt

jobs:
  include:
  - stage: "Black"
    script:
      - python setup.py build_ext --inplace
      - black --check fulqrum

  - stage: "Run tests"  
    script:
      - python setup.py build_ext --inplace
      - OPENBLAS_NUM_THREADS=1 pytest -p no:warnings fulqrum/test
  
  - stage: "Build docs"
    script:
      - python setup.py install
      - conda install pandoc
      - cd docs
      - make html
